### ISSUE TITLE
GetIO().FontDefault property missing setter.

### ISSUE THREAD

**Issue by BinarySpike** [raylib-extras/rlImGui-cs#3]
This is the format I identified for loading and changing a font:
```cs
var fontPtr = ImGui.GetIO().Fonts.AddFontFromFileTTF(@"path/to/font.ttf", 48f);
rlImGui.ReloadFonts();
unsafe {
    ImGui.GetIO().NativePtr->FontDefault = fontPtr.NativePtr;
}
```

Based on the [Dear Imgui Demo](https://github.com/ocornut/imgui/blob/cb48c81a448aa0a4867e327c0a045a708ff3842e/imgui_demo.cpp#L6135)

However, rlImGui-cs doesn't have the property setter on [ImGuiIOPtr](https://github.com/mellinoe/ImGui.NET/blob/6826b95b975b7e48674f99d8c086689bcb570a62/src/ImGui.NET/Generated/ImGuiIO.gen.cs#L783)

Is there a cleaner way or can we add this to the README?

**Comment by JeffM2501** [comment]
This is actually an issue with ImGui.net, not rlImGui, as we don't expose things in ImGui, just setup ImGui to use raylib. I don't think we need to bring up this in the rlImGui readme, because it's a general ImGui useage issue and not specific to this backend.

That said I've added a callback that you can install to insert new fonts during startup and not have to force the font to reload.
